[package]
name = "sevenshell"
version = "0.1.1"
license = "BSD-3-Clause"
edition = "2024"

[dependencies]
gio-unix = "0.22"
gtk4 = { version = "0.11.5", features = ["v4_12"] }
gtk4-layer-shell = "0.8.1"
gtk4-session-lock = { version = "0.4.1", features = ["v1_2"] }
pam-client = "0.5.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.6"
